/*
 
 eERRORES

TIENES DOS PLAYER CONTROLS UNO FUERA Y
OTRO DENTRO DE SCRIPT AVERIGUA CUAL ES EL BUENO

EN EL ASSEMBLY DEL SCRIPT 
HAY QUE METER EL TMP PARA QUE SE PUEDA USAR

VUELVE A CREAR TOOD DE 0 Y ASEGURRATE DE QUE ESTE BIEN
 
 */